### ISSUE TITLE
rws ./xtest defaultpath cannot succeed

### ISSUE THREAD

**Issue by jjinzhou** [BrendelGroup/SRAssembler#35]
Dear developer,
I encountered an error while running this step of the code, and I tried many methods but couldn't solve it. I really hope to receive your help.

rws ./xtest defaultpath
INFO:    Converting SIF file to temporary sandbox...
FATAL:   while extracting /home/NAS1/c3/lzh/au/phylogenomic_latest/SRAassembler/SRAssembler/demo/sra.sif: root filesystem extraction failed: extract command failed: WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount proc [kernel]: /proc doesn't exist in container
WARNING: Skipping mount /home/NAS1/c3/lzh/au/tools/singularity-ce-3.9.5/var/singularity/mnt/session/tmp [tmp]: /tmp doesn't exist in container
WARNING: Skipping mount /home/NAS1/c3/lzh/au/tools/singularity-ce-3.9.5/var/singularity/mnt/session/var/tmp [tmp]: /var/tmp doesn't exist in container
WARNING: Skipping mount /home/NAS1/c3/lzh/au/tools/singularity-ce-3.9.5/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
/usr/bin/unsquashfs: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
: exit status 127

But in fact, I can find this library
>  ls /lib/x86_64-linux-gnu/libz.so.1
 /lib/x86_64-linux-gnu/libz.so.1

I don't know where the problem is, I look forward to your reply

**Comment by vpbrendel** [comment]
It would seem that you did not define rws. In our instructions, this should be an alias. If you follow the instructions, the demo will work.
